== PP-Module for Web Browser 

[cols="1,1,1,1,1,1,1,1"]
|===
8+|webbrowser 
| https://github.com/commoncriteria/webbrowser/tree/master[master] 
a| https://commoncriteria.github.io/webbrowser/master/webbrowser-release.html[📄]
a|[link=https://github.com/commoncriteria/webbrowser/blob/gh-pages/master/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/webbrowser/gh-pages/master/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/webbrowser/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/webbrowser/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/webbrowser/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/webbrowser/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/webbrowser/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/webbrowser/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/webbrowser/gh-pages/master/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/webbrowser/blob/gh-pages/master/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/webbrowser/gh-pages/master/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/webbrowser/blob/gh-pages/master/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/webbrowser/gh-pages/master/pdf_count.svg[PDF Count]
|===

https://github.com/commoncriteria/webbrowser/issues[image:https://img.shields.io/github/issues/commoncriteria/webbrowser.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

This repository hosts the draft version of the PP-Module for Web Browser. The repository is used to facilitate collaboration and development on the draft document. 
See the [release](#Release-Version) section if you are looking for the officially released version for evaluations. 
A list of products that have passed evaluation against this Protection Profile can be found [here](https://www.niap-ccevs.org/Profile/Info.cfm?id=378).

=== Draft Version

* https://commoncriteria.github.io/webbrowser/master/webbrowser-release.html[PP-Module for Web Browsers] (html)

=== Release Version

* https://www.niap-ccevs.org/protectionprofiles/378[Extended Package for Web Browsers v2.0]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/webbrowser/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/webbrowser.git
....
To pull updates from the upstream _transforms_ submodule and commit them run:
....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.
You shouldn’t need to modify it.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
